### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by bradleyayers** [jrieken/ts-unused#2]
This project is a neat idea so I wanted to give it a try, but couldn't get it working:

```
$ node ../ts-unused/index.js -p tsconfig.json 
fs.js:910
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir '/Users/brad/projects/node_modules/@types'
    at Object.fs.readdirSync (fs.js:910:18)
    at Object.getDirectories (/Users/brad/projects/ts-unused/node_modules/typescript/lib/typescript.js:4310:38)
    at Object.getDirectories (/Users/brad/projects/ts-unused/node_modules/typescript/lib/typescript.js:71497:61)
    at Object.getDirectories (/Users/brad/projects/ts-unused/index.js:88:27)
    at Object.getDirectories (/Users/brad/projects/ts-unused/node_modules/typescript/lib/typescript.js:95420:55)
    at Object.getAutomaticTypeDirectiveNames (/Users/brad/projects/ts-unused/node_modules/typescript/lib/typescript.js:22757:52)
    at Object.createProgram (/Users/brad/projects/ts-unused/node_modules/typescript/lib/typescript.js:71812:37)
    at synchronizeHostData (/Users/brad/projects/ts-unused/node_modules/typescript/lib/typescript.js:95438:26)
    at Object.getProgram (/Users/brad/projects/ts-unused/node_modules/typescript/lib/typescript.js:95512:13)
    at Object.<anonymous> (/Users/brad/projects/ts-unused/index.js:174:28)
```

**Comment by aleksfront** [comment]
Observing exact same error.
